# Generated by Django 3.2.4 on 2021-06-20 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание работы')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона')),
                ('type', models.CharField(choices=[('office', 'Работа в офисе'), ('project', 'Разовая работа над проектом'), ('remote', 'Удаленная работа'), ('internship', 'Стажировка')], max_length=30, verbose_name='Тип работы')),
                ('salary', models.CharField(choices=[('monthly', 'Месячный оклад'), ('hourly', 'Почасовая оплата'), ('fixed', 'Фиксированная')], max_length=30, verbose_name='Оклад')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная зарплата')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальная зарплата')),
                ('currency', models.CharField(blank=True, choices=[('KGS', 'KGS'), ('USD', 'USD'), ('EURO', 'EURO'), ('RUB', 'RUB')], max_length=4, null=True, verbose_name='Валюта')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('is_expired', models.BooleanField(blank=True, default=False, verbose_name='Актуальность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Вакансия')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['created_at', 'updated_at'],
            },
        ),
    ]
