# Generated by Django 3.2.4 on 2021-06-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(blank=True, default=True, verbose_name='Подтвердить'),
        ),
    ]
